# fly.toml app configuration file generated for gandalf02 on 2024-02-09T11:44:12-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gandalf02'
primary_region = 'sea'

[build]

[[mounts]]
  source = 'chippy_data'
  destination = 'chippy_data'


